# Generated by Django 3.2.6 on 2022-02-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_addressdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdetails',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
