# Generated by Django 3.2.6 on 2022-02-16 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_addressdetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdetails',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.useraddress'),
        ),
    ]
