# Generated by Django 3.2.6 on 2022-02-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_addressdetails_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='is_dataRetrived',
            field=models.BooleanField(default=False),
        ),
    ]
