# Generated by Django 3.2.6 on 2022-02-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_addressdetails_numberchecked'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
