# Generated by Django 3.2.6 on 2022-02-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_useraddress_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='type',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
