# Generated by Django 3.2.6 on 2022-02-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_auto_20220218_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='addressTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.useraddress')),
                ('addressInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.addressdetails')),
            ],
        ),
    ]
