# Generated by Django 3.2.6 on 2022-02-21 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0015_addressdetailstags'),
    ]

    operations = [
        migrations.CreateModel(
            name='tagAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.addressdetails')),
                ('tags', models.ManyToManyField(blank=True, to='User.addressDetailsTags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
