# Generated by Django 3.2.6 on 2022-02-21 18:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0016_tagassigned'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tagAssigned',
            new_name='detailsTags',
        ),
    ]
